// Copyright 2022-2026 The sacloud/object-storage-api-go authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"time"
)

// CreateBucketParams is parameters of createBucket operation.
type CreateBucketParams struct {
	// バケット名.
	Name string
}

// CreatePermissionKeyParams is parameters of createPermissionKey operation.
type CreatePermissionKeyParams struct {
	// パーミッションID.
	ID string
}

// DeleteAccountKeyParams is parameters of deleteAccountKey operation.
type DeleteAccountKeyParams struct {
	// アクセスキーID.
	ID string
}

// DeleteBucketParams is parameters of deleteBucket operation.
type DeleteBucketParams struct {
	// バケット名.
	Name string
}

// DeleteBucketEncryptionParams is parameters of deleteBucketEncryption operation.
type DeleteBucketEncryptionParams struct {
	// バケット名.
	Name string
}

// DeleteBucketReplicationParams is parameters of deleteBucketReplication operation.
type DeleteBucketReplicationParams struct {
	// バケット名.
	Name string
}

// DeletePermissionParams is parameters of deletePermission operation.
type DeletePermissionParams struct {
	// パーミッションID.
	ID string
}

// DeletePermissionKeyParams is parameters of deletePermissionKey operation.
type DeletePermissionKeyParams struct {
	// パーミッションID.
	ID string
	// パーミッションが保有するアクセスキーID.
	KeyID string
}

// GetAccountKeyParams is parameters of getAccountKey operation.
type GetAccountKeyParams struct {
	// アクセスキーID.
	ID string
}

// GetBucketEncryptionParams is parameters of getBucketEncryption operation.
type GetBucketEncryptionParams struct {
	// バケット名.
	Name string
}

// GetBucketMeteringParams is parameters of getBucketMetering operation.
type GetBucketMeteringParams struct {
	// バケット名.
	Name BucketName
	// 範囲の開始月.
	From time.Time
	// 範囲の終了月.
	To time.Time
}

// GetBucketPenaltyParams is parameters of getBucketPenalty operation.
type GetBucketPenaltyParams struct {
	// バケット名.
	Name BucketName
}

// GetBucketPlanParams is parameters of getBucketPlan operation.
type GetBucketPlanParams struct {
	// バケット名.
	Name BucketName
}

// GetBucketQuotaParams is parameters of getBucketQuota operation.
type GetBucketQuotaParams struct {
	// バケット名.
	Name BucketName
}

// GetBucketReplicableTargetsParams is parameters of getBucketReplicableTargets operation.
type GetBucketReplicableTargetsParams struct {
	// バケット名.
	Name string
}

// GetBucketReplicationParams is parameters of getBucketReplication operation.
type GetBucketReplicationParams struct {
	// バケット名.
	Name string
}

// GetBucketUsageParams is parameters of getBucketUsage operation.
type GetBucketUsageParams struct {
	// バケット名.
	Name BucketName
}

// GetClusterParams is parameters of getCluster operation.
type GetClusterParams struct {
	// サイトID.
	ID string
}

// GetPermissionParams is parameters of getPermission operation.
type GetPermissionParams struct {
	// パーミッションID.
	ID string
}

// GetPermissionKeyParams is parameters of getPermissionKey operation.
type GetPermissionKeyParams struct {
	// パーミッションID.
	ID string
	// パーミッションが保有するアクセスキーID.
	KeyID string
}

// GetPermissionKeysParams is parameters of getPermissionKeys operation.
type GetPermissionKeysParams struct {
	// パーミッションID.
	ID string
}

// PostBucketReplicationParams is parameters of postBucketReplication operation.
type PostBucketReplicationParams struct {
	// バケット名.
	Name string
}

// PutBucketEncryptionParams is parameters of putBucketEncryption operation.
type PutBucketEncryptionParams struct {
	// バケット名.
	Name string
}

// PutBucketPlanParams is parameters of putBucketPlan operation.
type PutBucketPlanParams struct {
	// バケット名.
	Name BucketName
}

// UpdatePermissionParams is parameters of updatePermission operation.
type UpdatePermissionParams struct {
	// パーミッションID.
	ID string
}
