// Copyright 2022-2026 The sacloud/object-storage-api-go authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateAccountOperation              OperationName = "CreateAccount"
	CreateAccountKeyOperation           OperationName = "CreateAccountKey"
	CreateBucketOperation               OperationName = "CreateBucket"
	CreatePermissionOperation           OperationName = "CreatePermission"
	CreatePermissionKeyOperation        OperationName = "CreatePermissionKey"
	DeleteAccountOperation              OperationName = "DeleteAccount"
	DeleteAccountKeyOperation           OperationName = "DeleteAccountKey"
	DeleteBucketOperation               OperationName = "DeleteBucket"
	DeleteBucketEncryptionOperation     OperationName = "DeleteBucketEncryption"
	DeleteBucketReplicationOperation    OperationName = "DeleteBucketReplication"
	DeletePermissionOperation           OperationName = "DeletePermission"
	DeletePermissionKeyOperation        OperationName = "DeletePermissionKey"
	GetAccountOperation                 OperationName = "GetAccount"
	GetAccountKeyOperation              OperationName = "GetAccountKey"
	GetAccountKeysOperation             OperationName = "GetAccountKeys"
	GetBucketEncryptionOperation        OperationName = "GetBucketEncryption"
	GetBucketMeteringOperation          OperationName = "GetBucketMetering"
	GetBucketPenaltyOperation           OperationName = "GetBucketPenalty"
	GetBucketPlanOperation              OperationName = "GetBucketPlan"
	GetBucketQuotaOperation             OperationName = "GetBucketQuota"
	GetBucketReplicableTargetsOperation OperationName = "GetBucketReplicableTargets"
	GetBucketReplicationOperation       OperationName = "GetBucketReplication"
	GetBucketUsageOperation             OperationName = "GetBucketUsage"
	GetClusterOperation                 OperationName = "GetCluster"
	GetClustersOperation                OperationName = "GetClusters"
	GetPermissionOperation              OperationName = "GetPermission"
	GetPermissionKeyOperation           OperationName = "GetPermissionKey"
	GetPermissionKeysOperation          OperationName = "GetPermissionKeys"
	GetPermissionsOperation             OperationName = "GetPermissions"
	GetPlansOperation                   OperationName = "GetPlans"
	GetQuotaOperation                   OperationName = "GetQuota"
	GetStatusOperation                  OperationName = "GetStatus"
	ListBucketsOperation                OperationName = "ListBuckets"
	PostBucketReplicationOperation      OperationName = "PostBucketReplication"
	PutBucketEncryptionOperation        OperationName = "PutBucketEncryption"
	PutBucketPlanOperation              OperationName = "PutBucketPlan"
	UpdatePermissionOperation           OperationName = "UpdatePermission"
)
