// Copyright 2022-2026 The sacloud/object-storage-api-go authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.
package v1

type CreateAccountKeyRes interface {
	createAccountKeyRes()
}

type CreateAccountRes interface {
	createAccountRes()
}

type CreateBucketRes interface {
	createBucketRes()
}

type CreatePermissionKeyRes interface {
	createPermissionKeyRes()
}

type CreatePermissionRes interface {
	createPermissionRes()
}

type DeleteAccountKeyRes interface {
	deleteAccountKeyRes()
}

type DeleteAccountRes interface {
	deleteAccountRes()
}

type DeleteBucketEncryptionRes interface {
	deleteBucketEncryptionRes()
}

type DeleteBucketReplicationRes interface {
	deleteBucketReplicationRes()
}

type DeleteBucketRes interface {
	deleteBucketRes()
}

type DeletePermissionKeyRes interface {
	deletePermissionKeyRes()
}

type DeletePermissionRes interface {
	deletePermissionRes()
}

type GetAccountKeyRes interface {
	getAccountKeyRes()
}

type GetAccountKeysRes interface {
	getAccountKeysRes()
}

type GetAccountRes interface {
	getAccountRes()
}

type GetBucketEncryptionRes interface {
	getBucketEncryptionRes()
}

type GetBucketMeteringRes interface {
	getBucketMeteringRes()
}

type GetBucketPenaltyRes interface {
	getBucketPenaltyRes()
}

type GetBucketPlanRes interface {
	getBucketPlanRes()
}

type GetBucketQuotaRes interface {
	getBucketQuotaRes()
}

type GetBucketReplicableTargetsRes interface {
	getBucketReplicableTargetsRes()
}

type GetBucketReplicationRes interface {
	getBucketReplicationRes()
}

type GetBucketUsageRes interface {
	getBucketUsageRes()
}

type GetClusterRes interface {
	getClusterRes()
}

type GetClustersRes interface {
	getClustersRes()
}

type GetPermissionKeyRes interface {
	getPermissionKeyRes()
}

type GetPermissionKeysRes interface {
	getPermissionKeysRes()
}

type GetPermissionRes interface {
	getPermissionRes()
}

type GetPermissionsRes interface {
	getPermissionsRes()
}

type GetPlansRes interface {
	getPlansRes()
}

type GetQuotaRes interface {
	getQuotaRes()
}

type GetStatusRes interface {
	getStatusRes()
}

type ListBucketsRes interface {
	listBucketsRes()
}

type PostBucketReplicationRes interface {
	postBucketReplicationRes()
}

type PutBucketEncryptionRes interface {
	putBucketEncryptionRes()
}

type PutBucketPlanRes interface {
	putBucketPlanRes()
}

type UpdatePermissionRes interface {
	updatePermissionRes()
}
