// Copyright 2022-2026 The sacloud/object-storage-api-go authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"time"
)

// SetFake set fake values.
func (s *AccessKeyID) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = AccessKeyID(unwrapped)
}

// SetFake set fake values.
func (s *Account) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *AccountData) SetFake() {
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *AccountKey) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *AccountKeyData) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *AccountKeys) SetFake() {
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem AccountKeysDataItem
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *AccountKeysDataItem) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketBillingItem) SetFake() {
	{
		{
			s.YearMonth.SetFake()
		}
	}
	{
		{
			s.Basic.SetFake()
		}
	}
	{
		{
			s.StorageUsage.SetFake()
		}
	}
	{
		{
			s.NumObjects.SetFake()
		}
	}
	{
		{
			s.NumTransactions.SetFake()
		}
	}
	{
		{
			s.TransferAmount.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketBillingItemDetail) SetFake() {
	{
		{
			s.Found.SetFake()
		}
	}
	{
		{
			s.Usage.SetFake()
		}
	}
	{
		{
			s.Charge.SetFake()
		}
	}
	{
		{
			s.IsClosing.SetFake()
		}
	}
	{
		{
			s.From.SetFake()
		}
	}
	{
		{
			s.To.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketControls) SetFake() {
	var unwrapped []BucketControlsItem
	{
		unwrapped = nil
		for i := 0; i < 0; i++ {
			var elem BucketControlsItem
			{
				elem.SetFake()
			}
			unwrapped = append(unwrapped, elem)
		}
	}
	*s = BucketControls(unwrapped)
}

// SetFake set fake values.
func (s *BucketControlsItem) SetFake() {
	{
		{
			s.BucketName.SetFake()
		}
	}
	{
		{
			s.CanRead.SetFake()
		}
	}
	{
		{
			s.CanWrite.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketList) SetFake() {
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem BucketListDataItem
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *BucketListDataItem) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.Plan.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketListDataItemPlan) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.ServiceClassPath.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketName) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = BucketName(unwrapped)
}

// SetFake set fake values.
func (s *BucketPenalty) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketPenaltyData) SetFake() {
	{
		{
			s.NumObjectsPerBucket.SetFake()
		}
	}
	{
		{
			s.AmountGibPerBucket.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketPenaltyDataAmountGibPerBucket) SetFake() {
	{
		{
			s.Val.SetFake()
		}
	}
	{
		{
			s.Quota.SetFake()
		}
	}
	{
		{
			s.IsApplied.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketPenaltyDataNumObjectsPerBucket) SetFake() {
	{
		{
			s.Val.SetFake()
		}
	}
	{
		{
			s.Quota.SetFake()
		}
	}
	{
		{
			s.IsApplied.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketQuota) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketQuotaData) SetFake() {
	{
		{
			s.NumObjectsPerBucket.SetFake()
		}
	}
	{
		{
			s.AmountGibPerBucket.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketUsage) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *BucketUsageData) SetFake() {
	{
		{
			s.NumObjectsPerBucket.SetFake()
		}
	}
	{
		{
			s.AmountGibPerBucket.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *CanRead) SetFake() {
	var unwrapped bool
	{
		unwrapped = true
	}
	*s = CanRead(unwrapped)
}

// SetFake set fake values.
func (s *CanWrite) SetFake() {
	var unwrapped bool
	{
		unwrapped = true
	}
	*s = CanWrite(unwrapped)
}

// SetFake set fake values.
func (s *Code) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = Code(unwrapped)
}

// SetFake set fake values.
func (s *ContractSummary) SetFake() {
	{
		{
			s.ResourceID.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
	{
		{
			s.DeletedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ContractSummaryStatus) SetFake() {
	*s = ContractSummaryStatusActive
}

// SetFake set fake values.
func (s *CreatedAt) SetFake() {
	var unwrapped time.Time
	{
		unwrapped = time.Now()
	}
	*s = CreatedAt(unwrapped)
}

// SetFake set fake values.
func (s *DisplayName) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = DisplayName(unwrapped)
}

// SetFake set fake values.
func (s *Error400) SetFake() {
	{
		{
			s.Error.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Error400Error) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message.SetFake()
		}
	}
	{
		{
			s.TraceID.SetFake()
		}
	}
	{
		{
			s.Errors.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Error401) SetFake() {
	{
		{
			s.Error.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Error401Error) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message.SetFake()
		}
	}
	{
		{
			s.TraceID.SetFake()
		}
	}
	{
		{
			s.Errors.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Error403) SetFake() {
	{
		{
			s.Error.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Error403Error) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message.SetFake()
		}
	}
	{
		{
			s.TraceID.SetFake()
		}
	}
	{
		{
			s.Errors.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Error404) SetFake() {
	{
		{
			s.Error.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Error404Error) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message.SetFake()
		}
	}
	{
		{
			s.TraceID.SetFake()
		}
	}
	{
		{
			s.Errors.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Error409) SetFake() {
	{
		{
			s.Error.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Error409Error) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message.SetFake()
		}
	}
	{
		{
			s.TraceID.SetFake()
		}
	}
	{
		{
			s.Errors.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ErrorCode) SetFake() {
	var unwrapped int32
	{
		unwrapped = int32(0)
	}
	*s = ErrorCode(unwrapped)
}

// SetFake set fake values.
func (s *ErrorDefault) SetFake() {
	{
		{
			s.Error.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ErrorDefaultError) SetFake() {
	{
		{
			s.Code.SetFake()
		}
	}
	{
		{
			s.Message.SetFake()
		}
	}
	{
		{
			s.TraceID.SetFake()
		}
	}
	{
		{
			s.Errors.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ErrorMessage) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = ErrorMessage(unwrapped)
}

// SetFake set fake values.
func (s *ErrorTraceId) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = ErrorTraceId(unwrapped)
}

// SetFake set fake values.
func (s *Errors) SetFake() {
	var unwrapped []ErrorsItem
	{
		unwrapped = nil
		for i := 0; i < 0; i++ {
			var elem ErrorsItem
			{
				elem.SetFake()
			}
			unwrapped = append(unwrapped, elem)
		}
	}
	*s = Errors(unwrapped)
}

// SetFake set fake values.
func (s *ErrorsDomain) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = ErrorsDomain(unwrapped)
}

// SetFake set fake values.
func (s *ErrorsItem) SetFake() {
	{
		{
			s.Domain.SetFake()
		}
	}
	{
		{
			s.Location.SetFake()
		}
	}
	{
		{
			s.LocationType.SetFake()
		}
	}
	{
		{
			s.Message.SetFake()
		}
	}
	{
		{
			s.Reason.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ErrorsLocation) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = ErrorsLocation(unwrapped)
}

// SetFake set fake values.
func (s *ErrorsLocationType) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = ErrorsLocationType(unwrapped)
}

// SetFake set fake values.
func (s *ErrorsMessage) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = ErrorsMessage(unwrapped)
}

// SetFake set fake values.
func (s *ErrorsReason) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = ErrorsReason(unwrapped)
}

// SetFake set fake values.
func (s *GetBucketEncryptionOK) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetBucketMeteringOK) SetFake() {
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem BucketBillingItem
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *GetBucketPlanOK) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *GetPlansOK) SetFake() {
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem PlanItem
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerEncryptionConfigReqBody) SetFake() {
	{
		{
			s.KmsKeyID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerEncryptionConfigRes) SetFake() {
	{
		{
			s.KmsKeyID.SetFake()
		}
	}
	{
		{
			s.ConfiguredAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerGetClusterRes) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerGetReplicableTargetsRes) SetFake() {
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem ModelBucket
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerGetReplicationRes) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerListClustersRes) SetFake() {
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem ModelCluster
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *HandlerPostReplicationRes) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerPutBucketReqBody) SetFake() {
	{
		{
			s.ClusterID = "string"
		}
	}
	{
		{
			s.Plan.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerPutBucketReqBodyPlan) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.ServiceClassPath.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *HandlerPutBucketRes) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelBucket) SetFake() {
	{
		{
			s.ClusterID.SetFake()
		}
	}
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.Plan.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelBucketPlan) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.ServiceClassPath.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelCluster) SetFake() {
	{
		{
			s.APIZone = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.APIZone = append(s.APIZone, elem)
			}
		}
	}
	{
		{
			s.ControlPanelURL.SetFake()
		}
	}
	{
		{
			s.DisplayNameEnUs.SetFake()
		}
	}
	{
		{
			s.DisplayNameJa.SetFake()
		}
	}
	{
		{
			s.DisplayName.SetFake()
		}
	}
	{
		{
			s.DisplayOrder.SetFake()
		}
	}
	{
		{
			s.EndpointBase.SetFake()
		}
	}
	{
		{
			s.IamEndpoint.SetFake()
		}
	}
	{
		{
			s.IamEndpointForControlPanel.SetFake()
		}
	}
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Region.SetFake()
		}
	}
	{
		{
			s.S3Endpoint.SetFake()
		}
	}
	{
		{
			s.S3EndpointForControlPanel.SetFake()
		}
	}
	{
		{
			s.StorageZone = nil
			for i := 0; i < 0; i++ {
				var elem string
				{
					elem = "string"
				}
				s.StorageZone = append(s.StorageZone, elem)
			}
		}
	}
	{
		{
			s.PlanFamily.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelClusterPlanFamily) SetFake() {
	*s = ModelClusterPlanFamilyStandard
}

// SetFake set fake values.
func (s *ModelPlanType) SetFake() {
	*s = ModelPlanTypeStandard
}

// SetFake set fake values.
func (s *ModelReplication) SetFake() {
	{
		{
			s.SourceBucket.SetFake()
		}
	}
	{
		{
			s.DestBucket.SetFake()
		}
	}
	{
		{
			s.ConfigStatus.SetFake()
		}
	}
	{
		{
			s.CreatedAt = time.Now()
		}
	}
}

// SetFake set fake values.
func (s *ModelReplicationConfigStatus) SetFake() {
	*s = ModelReplicationConfigStatusCreating
}

// SetFake set fake values.
func (s *ModelReplicationDestBucket) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.ClusterID.SetFake()
		}
	}
	{
		{
			s.Plan.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelReplicationDestBucketPlan) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.ServiceClassPath.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelReplicationSourceBucket) SetFake() {
	{
		{
			s.Name.SetFake()
		}
	}
	{
		{
			s.ClusterID.SetFake()
		}
	}
	{
		{
			s.Plan.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ModelReplicationSourceBucketPlan) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.ServiceClassPath.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *OptAccessKeyID) SetFake() {
	var elem AccessKeyID
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptAccountData) SetFake() {
	var elem AccountData
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptAccountKeyData) SetFake() {
	var elem AccountKeyData
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBool) SetFake() {
	var elem bool
	{
		elem = true
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBucketBillingItemDetail) SetFake() {
	var elem BucketBillingItemDetail
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBucketListDataItemPlan) SetFake() {
	var elem BucketListDataItemPlan
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBucketName) SetFake() {
	var elem BucketName
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBucketPenaltyData) SetFake() {
	var elem BucketPenaltyData
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBucketPenaltyDataAmountGibPerBucket) SetFake() {
	var elem BucketPenaltyDataAmountGibPerBucket
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBucketPenaltyDataNumObjectsPerBucket) SetFake() {
	var elem BucketPenaltyDataNumObjectsPerBucket
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBucketQuotaData) SetFake() {
	var elem BucketQuotaData
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptBucketUsageData) SetFake() {
	var elem BucketUsageData
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCanRead) SetFake() {
	var elem CanRead
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCanWrite) SetFake() {
	var elem CanWrite
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCode) SetFake() {
	var elem Code
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptContractSummary) SetFake() {
	var elem ContractSummary
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptContractSummaryStatus) SetFake() {
	var elem ContractSummaryStatus
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptCreatedAt) SetFake() {
	var elem CreatedAt
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptDate) SetFake() {
	var elem time.Time
	{
		elem = time.Now()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptDateTime) SetFake() {
	var elem time.Time
	{
		elem = time.Now()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptDisplayName) SetFake() {
	var elem DisplayName
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptError400Error) SetFake() {
	var elem Error400Error
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptError401Error) SetFake() {
	var elem Error401Error
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptError403Error) SetFake() {
	var elem Error403Error
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptError404Error) SetFake() {
	var elem Error404Error
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptError409Error) SetFake() {
	var elem Error409Error
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptErrorCode) SetFake() {
	var elem ErrorCode
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptErrorDefaultError) SetFake() {
	var elem ErrorDefaultError
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptErrorMessage) SetFake() {
	var elem ErrorMessage
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptErrorTraceId) SetFake() {
	var elem ErrorTraceId
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptErrorsDomain) SetFake() {
	var elem ErrorsDomain
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptErrorsLocation) SetFake() {
	var elem ErrorsLocation
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptErrorsLocationType) SetFake() {
	var elem ErrorsLocationType
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptErrorsMessage) SetFake() {
	var elem ErrorsMessage
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptErrorsReason) SetFake() {
	var elem ErrorsReason
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptFloat32) SetFake() {
	var elem float32
	{
		elem = float32(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptFloat64) SetFake() {
	var elem float64
	{
		elem = float64(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptInt) SetFake() {
	var elem int
	{
		elem = int(0)
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelBucket) SetFake() {
	var elem ModelBucket
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelBucketPlan) SetFake() {
	var elem ModelBucketPlan
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelCluster) SetFake() {
	var elem ModelCluster
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelClusterPlanFamily) SetFake() {
	var elem ModelClusterPlanFamily
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelPlanType) SetFake() {
	var elem ModelPlanType
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelReplication) SetFake() {
	var elem ModelReplication
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelReplicationDestBucketPlan) SetFake() {
	var elem ModelReplicationDestBucketPlan
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptModelReplicationSourceBucketPlan) SetFake() {
	var elem ModelReplicationSourceBucketPlan
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptNilDateTime) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilHandlerPutBucketReqBodyPlan) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilInt) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptNilPlanItemFee) SetFake() {
	s.Null = true
	s.Set = true
}

// SetFake set fake values.
func (s *OptPermissionData) SetFake() {
	var elem PermissionData
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPermissionID) SetFake() {
	var elem PermissionID
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPermissionKeyData) SetFake() {
	var elem PermissionKeyData
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPermissionKeyID) SetFake() {
	var elem PermissionKeyID
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPermissionSecret) SetFake() {
	var elem PermissionSecret
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptPlanSummary) SetFake() {
	var elem PlanSummary
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptQuotaData) SetFake() {
	var elem QuotaData
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptResourceID) SetFake() {
	var elem ResourceID
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptSecretAccessKey) SetFake() {
	var elem SecretAccessKey
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptServiceClassPath) SetFake() {
	var elem ServiceClassPath
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptStatusData) SetFake() {
	var elem StatusData
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptStatusDataStatusCode) SetFake() {
	var elem StatusDataStatusCode
	{
		elem.SetFake()
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *OptString) SetFake() {
	var elem string
	{
		elem = "string"
	}
	s.SetTo(elem)
}

// SetFake set fake values.
func (s *Permission) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PermissionBucketControlsBody) SetFake() {
	{
		{
			s.DisplayName.SetFake()
		}
	}
	{
		{
			s.BucketControls.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PermissionData) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.DisplayName.SetFake()
		}
	}
	{
		{
			s.BucketControls.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PermissionID) SetFake() {
	var unwrapped int64
	{
		unwrapped = int64(0)
	}
	*s = PermissionID(unwrapped)
}

// SetFake set fake values.
func (s *PermissionKey) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PermissionKeyData) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PermissionKeyID) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = PermissionKeyID(unwrapped)
}

// SetFake set fake values.
func (s *PermissionKeys) SetFake() {
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem PermissionKeysDataItem
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PermissionKeysDataItem) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Secret.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PermissionSecret) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = PermissionSecret(unwrapped)
}

// SetFake set fake values.
func (s *Permissions) SetFake() {
	{
		{
			s.Data = nil
			for i := 0; i < 0; i++ {
				var elem PermissionsDataItem
				{
					elem.SetFake()
				}
				s.Data = append(s.Data, elem)
			}
		}
	}
}

// SetFake set fake values.
func (s *PermissionsDataItem) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.DisplayName.SetFake()
		}
	}
	{
		{
			s.BucketControls.SetFake()
		}
	}
	{
		{
			s.CreatedAt.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PlanChangeReqBody) SetFake() {
	{
		{
			s.PreviousContract.SetFake()
		}
	}
	{
		{
			s.NewPlan.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PlanChangeReqBodyNewPlan) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.ServiceClassPath.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PlanChangeReqBodyPreviousContract) SetFake() {
	{
		{
			s.ResourceID.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PlanChangeResBody) SetFake() {
	{
		{
			s.PreviousContract.SetFake()
		}
	}
	{
		{
			s.NewContract.SetFake()
		}
	}
	{
		{
			s.Plan.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PlanItem) SetFake() {
	{
		{
			s.ServiceClassPath.SetFake()
		}
	}
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.ClusterID.SetFake()
		}
	}
	{
		{
			s.CapacityGib.SetFake()
		}
	}
	{
		{
			s.Fee.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PlanItemFee) SetFake() {
	{
		{
			s.ForMonth.SetFake()
		}
	}
	{
		{
			s.Monthly.SetFake()
		}
	}
	{
		{
			s.Daily.SetFake()
		}
	}
	{
		{
			s.Hourly.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PlanSummary) SetFake() {
	{
		{
			s.Type.SetFake()
		}
	}
	{
		{
			s.ServiceClassPath.SetFake()
		}
	}
	{
		{
			s.ClusterID.SetFake()
		}
	}
	{
		{
			s.CapacityGib.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PlanWithContract) SetFake() {
	{
		{
			s.Plan.SetFake()
		}
	}
	{
		{
			s.Contract.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PostBucketReplicationReq) SetFake() {
	{
		{
			s.DestBucket = "string"
		}
	}
}

// SetFake set fake values.
func (s *PutBucketEncryptionOK) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *PutBucketPlanOK) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *Quota) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *QuotaData) SetFake() {
	{
		{
			s.NumRootKeys.SetFake()
		}
	}
	{
		{
			s.NumBuckets.SetFake()
		}
	}
	{
		{
			s.NumPermissions.SetFake()
		}
	}
	{
		{
			s.NumKeysPerPermission.SetFake()
		}
	}
	{
		{
			s.NumBucketsPerPermission.SetFake()
		}
	}
	{
		{
			s.NumObjectsPerBucket.SetFake()
		}
	}
	{
		{
			s.AmountGibPerBucket.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *ResourceID) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = ResourceID(unwrapped)
}

// SetFake set fake values.
func (s *SecretAccessKey) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = SecretAccessKey(unwrapped)
}

// SetFake set fake values.
func (s *ServiceClassPath) SetFake() {
	var unwrapped string
	{
		unwrapped = "string"
	}
	*s = ServiceClassPath(unwrapped)
}

// SetFake set fake values.
func (s *Status) SetFake() {
	{
		{
			s.Data.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *StatusData) SetFake() {
	{
		{
			s.AcceptNew.SetFake()
		}
	}
	{
		{
			s.Message.SetFake()
		}
	}
	{
		{
			s.StartedAt.SetFake()
		}
	}
	{
		{
			s.StatusCode.SetFake()
		}
	}
}

// SetFake set fake values.
func (s *StatusDataStatusCode) SetFake() {
	{
		{
			s.ID.SetFake()
		}
	}
	{
		{
			s.Status.SetFake()
		}
	}
}
