// Copyright 2022-2026 The sacloud/object-storage-api-go authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// BasicAuth provides BasicAuth security value.
	// [クラウドコントロールパネル](https://secure.sakura.ad.
	// jp/cloud/)で発行したAPIキーを利用します。
	// `アクセストークン(UUID)`
	// を「ユーザーID」、`アクセストークンシークレット`
	// を「パスワード」として指定します。.
	BasicAuth(ctx context.Context, operationName OperationName) (BasicAuth, error)
}

func (s *Client) securityBasicAuth(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.BasicAuth(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"BasicAuth\"")
	}
	req.SetBasicAuth(t.Username, t.Password)
	return nil
}
